FROM node:18-alpine AS frontend-build
WORKDIR /app/frontend
COPY revtickets-frontend/package*.json ./
RUN npm install --legacy-peer-deps
COPY revtickets-frontend/ ./
RUN npm run build

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=frontend-build /app/frontend/dist/rev-ticket/browser /app/static
COPY revtickets-backend/target/*.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
